# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 18:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Memento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('archive', models.CharField(choices=[('archive.org', 'archive.org')], db_index=True, default='archive.org', max_length=1000)),
                ('url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='clip',
            name='memento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.Memento'),
        ),
        migrations.AddField(
            model_name='clip',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
