# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 03:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clip',
            options={'ordering': ('-memento__timestamp',)},
        ),
        migrations.AlterModelOptions(
            name='memento',
            options={'ordering': ('-timestamp',)},
        ),
        migrations.AddField(
            model_name='clip',
            name='mementos',
            field=models.ManyToManyField(to='archive.Memento'),
        ),
        migrations.AlterField(
            model_name='clip',
            name='memento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_memento', to='archive.Memento'),
        ),
    ]
