# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 04:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0004_auto_20171115_0409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clip',
            options={},
        ),
        migrations.AlterModelOptions(
            name='memento',
            options={'get_latest_by': 'timestamp', 'ordering': ('-timestamp',)},
        ),
    ]
