# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 04:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0006_auto_20171115_0420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clip',
            name='memento',
        ),
    ]
