# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0007_remove_clip_memento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memento',
            name='archive',
            field=models.CharField(choices=[('archive.org', 'archive.org'), ('archive.is', 'archive.is')], db_index=True, default='archive.org', max_length=1000),
        ),
    ]
