name: Build
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install
        run: npm ci

      - name: Build
        run: |
          npm run-script build
          echo 'savemy.news' > _dist/CNAME
          touch _dist/.nojekyll
          echo 'encoding: UTF-8' > _dist/_config.yml

      - name: Setup Pages
        uses: actions/configure-pages@v2.1.3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: _dist

  deploy:
    name: Deploy
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1.2.3