name: Tests
on: push

jobs:
  test:
    name: Test 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install dependencies
        uses: ./.github/actions/install-pipenv 
      
      - name: Run
        run: |
            export SECRET_KEY='this is not a secret key'
            make test
